[workspace]
resolver = "2"
members = [
    "crates/tarvos-cli",
    "crates/tarvos-server",
    "crates/tarvos-core",
    "crates/tarvos-ast",
    "crates/tarvos-parser",
    "crates/tarvos-types",
    "crates/tarvos-ir",
    "crates/tarvos-analysis",
    "crates/tarvos-optimizer",
    "crates/tarvos-codegen-rust",
    "crates/tarvos-tests",
]

[profile.dev]
incremental = true
codegen-units = 8
debug = 0
opt-level = 0

[profile.release]
opt-level = "z"
codegen-units = 1
lto = true
debug = 0
panic = "abort"
strip = true

[profile.release-fast]
inherits = "release"
opt-level = 3
codegen-units = 8
lto = false
panic = "abort"
strip = "symbols"
