#!/usr/bin/env python3
"""Print the RELEASE_NOTES.md section for one release tag.

RELEASE_NOTES.md is the single canonical source for release bodies: the body
is generated from one section of one file instead of being auto-generated by
GitHub, and auto-generation used to append a second "Full Changelog" block to
the hand-written one.

    python scripts/extract_release_notes.py v1.1.0-rc.3 > release-body.md

Exits non-zero when the tag has no section, when the section is too short to
describe a release, or when it would emit more than one comparison link,
because publishing an empty, generic, or duplicated body is worse than failing
the release job. Historical sections are allowed to omit the link; the rule
only forbids emitting it twice.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COMPARE_PREFIX = "https://github.com/repo-tech/tarvos/compare/"


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2

    tag = argv[1].strip()
    version = tag.lstrip("v")
    notes = (ROOT / "RELEASE_NOTES.md").read_text(encoding="utf-8")

    header = f"# Tarvos {version}"
    start = notes.find(header)
    if start == -1:
        print(f"RELEASE_NOTES.md has no section for {header!r}", file=sys.stderr)
        return 1

    rest = notes[start + len(header) :]
    next_section = re.search(r"(?m)^# Tarvos ", rest)
    section = header + (rest[: next_section.start()] if next_section else rest)
    section = section.strip() + "\n"

    if len(section.splitlines()) < 3:
        print(f"RELEASE_NOTES.md section for {tag} is empty", file=sys.stderr)
        return 1

    links = re.findall(re.escape(COMPARE_PREFIX) + r"\S+", section)
    if len(links) > 1:
        print(
            f"RELEASE_NOTES.md section for {tag} has {len(links)} comparison links, "
            f"expected at most 1: {links}",
            file=sys.stderr,
        )
        return 1

    # Emit UTF-8 bytes rather than text. The default stdout encoding on Windows
    # is the console code page, which silently mangles the em dashes in the
    # notes into invalid UTF-8 and corrupts the published release body.
    sys.stdout.buffer.write(section.encode("utf-8"))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
