#!/usr/bin/env python3
"""Print the RELEASE_NOTES.md section for one release tag.

RELEASE_NOTES.md is the single canonical source for release bodies: the body
is generated from one section of one file instead of being auto-generated by
GitHub, and auto-generation used to append a second "Full Changelog" block to
the hand-written one.

    python scripts/extract_release_notes.py v1.1.0-rc.3 > release-body.md

Exits non-zero when the tag has no section, when the section is too short to
describe a release, when it carries more than one comparison link, or when the
section for the current workspace version is missing a required heading.
Publishing an empty, generic, duplicated, or structurally incomplete body is
worse than failing the release job.

Structural rules apply to the section for the current workspace version only.
Historical sections are left alone: they were published before these rules
existed, and rewriting or re-validating shipped history is not this script's
job. The comparison-link rule still applies to every section, because a
duplicated link is a defect wherever it appears.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COMPARE_PREFIX = "https://github.com/repo-tech/tarvos/compare/"

# A release body has to answer "what is in this, what breaks, how do I verify
# it, and how do I install it". These four headings are the minimum that makes a
# body usable; rc.3 already has all of them plus twelve more.
REQUIRED_SECTIONS = (
    "## Highlights",
    "## Breaking Changes",
    "## Validation",
    "## Installation",
)


def workspace_version() -> str | None:
    """Read the version from the workspace Cargo.toml, or None if unreadable.

    Used only to decide whether the structural rules apply. If the manifest
    cannot be read the rules are skipped rather than guessed, so a formatting
    change to Cargo.toml cannot block a release.
    """
    manifest = (ROOT / "Cargo.toml").read_text(encoding="utf-8")
    match = re.search(r'(?m)^version = "([^"]+)"', manifest)
    return match.group(1) if match else None


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2

    tag = argv[1].strip()
    version = tag.lstrip("v")
    notes = (ROOT / "RELEASE_NOTES.md").read_text(encoding="utf-8")

    header = f"# Tarvos {version}"
    start = notes.find(header)
    if start == -1:
        print(f"RELEASE_NOTES.md has no section for {header!r}", file=sys.stderr)
        return 1

    rest = notes[start + len(header) :]
    next_section = re.search(r"(?m)^# Tarvos ", rest)
    section = header + (rest[: next_section.start()] if next_section else rest)
    section = section.strip() + "\n"

    if len(section.splitlines()) < 3:
        print(f"RELEASE_NOTES.md section for {tag} is empty", file=sys.stderr)
        return 1

    links = re.findall(re.escape(COMPARE_PREFIX) + r"\S+", section)
    if len(links) > 1:
        print(
            f"RELEASE_NOTES.md section for {tag} has {len(links)} comparison links, "
            f"expected at most 1: {links}",
            file=sys.stderr,
        )
        return 1

    # Structural rules, for the release currently being cut only. Re-running an
    # old tag must keep working, so a historical section is never rejected for
    # a shape it was published without.
    if workspace_version() == version:
        headings = set(re.findall(r"(?m)^##\s+(.+?)\s*$", section))
        missing = [name for name in REQUIRED_SECTIONS if name.removeprefix("## ") not in headings]
        if missing:
            print(
                f"RELEASE_NOTES.md section for {tag} is missing required "
                f"section(s): {', '.join(missing)}",
                file=sys.stderr,
            )
            return 1

    # Emit UTF-8 bytes rather than text. The default stdout encoding on Windows
    # is the console code page, which silently mangles the em dashes in the
    # notes into invalid UTF-8 and corrupts the published release body.
    sys.stdout.buffer.write(section.encode("utf-8"))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
